import { ExamResult } from '../types/dashboard';

// Seed dataset representing learner exam attempts across multiple exam types and dates.
export const examResults: ExamResult[] = [
  {
    attemptId: 'att-001',
    learnerId: 'learner-001',
    learnerName: 'Anan Chai',
    examId: 'exam-english-001',
    examTitle: 'English Placement Test',
    examType: 'placement',
    score: 78,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-01-10T08:35:00.000Z',
  },
  {
    attemptId: 'att-002',
    learnerId: 'learner-002',
    learnerName: 'Benja Thong',
    examId: 'exam-english-001',
    examTitle: 'English Placement Test',
    examType: 'placement',
    score: 92,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'advanced',
    completedAt: '2024-02-15T09:12:00.000Z',
  },
  {
    attemptId: 'att-003',
    learnerId: 'learner-003',
    learnerName: 'Chanita Mee',
    examId: 'exam-english-002',
    examTitle: 'English Final Exam',
    examType: 'final',
    score: 61,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-03-02T12:01:00.000Z',
  },
  {
    attemptId: 'att-004',
    learnerId: 'learner-004',
    learnerName: 'Darin Kitt',
    examId: 'exam-english-002',
    examTitle: 'English Final Exam',
    examType: 'final',
    score: 48,
    maxScore: 100,
    passed: false,
    proficiencyLevel: 'beginner',
    completedAt: '2024-03-18T11:25:00.000Z',
  },
  {
    attemptId: 'att-005',
    learnerId: 'learner-005',
    learnerName: 'Ekachai Wip',
    examId: 'exam-english-003',
    examTitle: 'Business English Quiz',
    examType: 'quiz',
    score: 85,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'advanced',
    completedAt: '2024-04-05T06:45:00.000Z',
  },
  {
    attemptId: 'att-006',
    learnerId: 'learner-002',
    learnerName: 'Benja Thong',
    examId: 'exam-english-003',
    examTitle: 'Business English Quiz',
    examType: 'quiz',
    score: 88,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'advanced',
    completedAt: '2024-04-12T06:45:00.000Z',
  },
  {
    attemptId: 'att-007',
    learnerId: 'learner-006',
    learnerName: 'Fah Sir',
    examId: 'exam-english-004',
    examTitle: 'Listening Comprehension Test',
    examType: 'practice',
    score: 55,
    maxScore: 100,
    passed: false,
    proficiencyLevel: 'beginner',
    completedAt: '2024-05-01T10:05:00.000Z',
  },
  {
    attemptId: 'att-008',
    learnerId: 'learner-007',
    learnerName: 'Gamon Kaeo',
    examId: 'exam-english-005',
    examTitle: 'Grammar Challenge',
    examType: 'quiz',
    score: 73,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-05-10T09:32:00.000Z',
  },
  {
    attemptId: 'att-009',
    learnerId: 'learner-008',
    learnerName: 'Hansa Lum',
    examId: 'exam-english-002',
    examTitle: 'English Final Exam',
    examType: 'final',
    score: 97,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'expert',
    completedAt: '2024-06-08T14:20:00.000Z',
  },
  {
    attemptId: 'att-010',
    learnerId: 'learner-009',
    learnerName: 'Issara Poon',
    examId: 'exam-english-001',
    examTitle: 'English Placement Test',
    examType: 'placement',
    score: 67,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-06-15T08:55:00.000Z',
  },
  {
    attemptId: 'att-011',
    learnerId: 'learner-010',
    learnerName: 'Jinda Kwan',
    examId: 'exam-english-006',
    examTitle: 'Advanced Speaking Assessment',
    examType: 'assessment',
    score: 82,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'advanced',
    completedAt: '2024-06-20T16:10:00.000Z',
  },
  {
    attemptId: 'att-012',
    learnerId: 'learner-001',
    learnerName: 'Anan Chai',
    examId: 'exam-english-006',
    examTitle: 'Advanced Speaking Assessment',
    examType: 'assessment',
    score: 89,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'advanced',
    completedAt: '2024-06-28T10:15:00.000Z',
  },
  {
    attemptId: 'att-013',
    learnerId: 'learner-011',
    learnerName: 'Kanya Jai',
    examId: 'exam-english-004',
    examTitle: 'Listening Comprehension Test',
    examType: 'practice',
    score: 46,
    maxScore: 100,
    passed: false,
    proficiencyLevel: 'beginner',
    completedAt: '2024-07-02T07:22:00.000Z',
  },
  {
    attemptId: 'att-014',
    learnerId: 'learner-012',
    learnerName: 'Lalana Pre',
    examId: 'exam-english-007',
    examTitle: 'Vocabulary Drill',
    examType: 'practice',
    score: 58,
    maxScore: 100,
    passed: false,
    proficiencyLevel: 'beginner',
    completedAt: '2024-07-18T07:45:00.000Z',
  },
  {
    attemptId: 'att-015',
    learnerId: 'learner-013',
    learnerName: 'Manot Ric',
    examId: 'exam-english-002',
    examTitle: 'English Final Exam',
    examType: 'final',
    score: 74,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-08-02T10:18:00.000Z',
  },
  {
    attemptId: 'att-016',
    learnerId: 'learner-014',
    learnerName: 'Napas Orn',
    examId: 'exam-english-003',
    examTitle: 'Business English Quiz',
    examType: 'quiz',
    score: 94,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'expert',
    completedAt: '2024-08-18T13:58:00.000Z',
  },
  {
    attemptId: 'att-017',
    learnerId: 'learner-015',
    learnerName: 'Orasa Chon',
    examId: 'exam-english-001',
    examTitle: 'English Placement Test',
    examType: 'placement',
    score: 52,
    maxScore: 100,
    passed: false,
    proficiencyLevel: 'beginner',
    completedAt: '2024-08-25T09:44:00.000Z',
  },
  {
    attemptId: 'att-018',
    learnerId: 'learner-016',
    learnerName: 'Panna Rit',
    examId: 'exam-english-005',
    examTitle: 'Grammar Challenge',
    examType: 'quiz',
    score: 63,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-09-03T11:02:00.000Z',
  },
  {
    attemptId: 'att-019',
    learnerId: 'learner-017',
    learnerName: 'Q Boon',
    examId: 'exam-english-006',
    examTitle: 'Advanced Speaking Assessment',
    examType: 'assessment',
    score: 76,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-09-12T15:22:00.000Z',
  },
  {
    attemptId: 'att-020',
    learnerId: 'learner-018',
    learnerName: 'Rati Duen',
    examId: 'exam-english-007',
    examTitle: 'Vocabulary Drill',
    examType: 'practice',
    score: 69,
    maxScore: 100,
    passed: true,
    proficiencyLevel: 'intermediate',
    completedAt: '2024-09-20T08:40:00.000Z',
  },
];
